clear all
clc
%% Condition Parameters
k_n = [.0378 .042]; % Conductivity Neoprene W/K m
%h_waterforced=Derived Below;% Water Forced Convection W/K m^2
%h_waternatural=Derived Below; %Water Natural Convection W/K m^2
%h_airforced= Derived Below;% Air Forced Convection W/K m^2
%h_airnatural=Derived Below; %Air Natural Convection W/K m^2
A=1.95; % Surface Area of body m^2
T_H=35; % Temperature Body Celsius
T_W=0; %Temperature Water
T_A=-6; %Temperature Wind Chill
L=0.005; % Thickness of Neoprene
%% Air Parameters
g=9.81; %Gravity
Beta_air=0.0034; %Thermal Expansion Coefficent
DT_suit=15;% Change in Temp body to air in suit
L_body=2; %Length of Body (m)
v_air=.000014;% Kinematic Viscosity
alpha_air=.000022; %Thermal Diffusivity of Air
k_air=.02624; %Thermal Conductivity of Air
Pr_air=.712;% Prandtl Number of Air at 0C
mu_air= 17.15*10^(-6); %Dynamic Viscosity of air at 0C
U_air=12; %Wind Speed (m/s)
rho_air= 1.22; % Density of Air
%% Water Parameters

k_water=0.555; %Thermal Conductivity Water
L_body=2; %Length of Body
Pr_water=13.6; %Prandtl number of Water at 0 C
mu_water=0.00179;% Dynamic Viscosity at 0C
U_water=1.5; %Speed of Water (m/s)
rho_water=1000; %Density of Water


%% Now we will Derive Heat Transfer Coefficents for Air and Water
% Will be derived in the case of Forced and Natural Convection
%% Water Forced Convection Coefficient 
% Flat Sheet in Turbulent Conditions model

Re_L_water=rho_water*U_water*L_body/mu_water; %Reynolds Number
Re_t_water=500000; % Lack of vibrations
Nu_1_water=0.664*Re_t_water^.5 *Pr_water^.333 +0.036*Re_L_water^0.8*Pr_water^.43*[1-(Re_t_water/Re_L_water)^0.8];% Turbulent
Nu_2_water=0.664*Re_L_water^.5*Pr_water^.333; %Laminar

h_waterforced=Nu_1_water*k_water/L_body;

%% Air Natural Convection Coefficient
% Natural Convection on flat sheet model
Ra_airnatural= g*Beta_air*DT_suit* L_body^3/(v_air*alpha_air);
Nu_airnatural= 0.14* Ra_airnatural^.333;

h_airnatural= Nu_airnatural*k_air/L_body;

%% Air Forced Convection Coefficent
% Flat Sheet in Turbulent Conditions model

Re_L_air=rho_water*U_water*L_body/mu_water;
Re_t_air=500000;
Nu_1_air=0.664*Re_t_air^.5 *Pr_air^.333 +0.036*Re_L_air^0.8*Pr_air^.43*[1-(Re_t_air/Re_L_air)^0.8];% Turbulent
Nu_2_air=0.664*Re_L_air^.5*Pr_air^.333; %Laminar

h_airforced=Nu_1_air*k_air/L_body;

%% Now we will find the heat losses of a body in survival suit
% Half of body submerged in Water, half above water
% Two different means of heat loss, above and below water
%% Heat Loss below water (To water)
%Human- Neoprene (Conduct.)- Water(Forced Conv.)

R_EW= L./(k_n.*A/2)+1/(h_waterforced*A/2);
Q_LossWater= (T_H-T_W)./R_EW;


%% Heat loss above water (To Air)
% Body- Air Gap(Natural Convection)- Neoprene (Conductivity)- Air (Forced)

R_EA= 1/(h_airnatural*A/2)+L./(k_n.*A/2)+1/(h_airforced* A/2);
Q_LossAir= (T_H-T_A)./R_EA;

%% Total Heat Loss
Q_LossTotal= Q_LossWater+ Q_LossAir;

%% Net Loss
Q_Human=200; %Heat generated by Human
Q_NetLoss= Q_LossTotal-Q_Human;

body_heat_dissipation = strcat(num2str(Q_Human),'W');
lower_bound = strcat(num2str(Q_NetLoss(1)),'W');
upper_bound = strcat(num2str(Q_NetLoss(2)),'W');

display(body_heat_dissipation)
display(lower_bound)
display(upper_bound)
